# Transaction exclusion rules
# Transactions matching these patterns will be excluded from analysis
# Source IDs must match those defined in app/constants.py:
#   - chase_checking
#   - chase_credit_card  
#   - apple_card_joe
#   - apple_card_nikita

exclusions:
  # Card payments (to avoid double counting transfers between accounts)
  - source: "apple_card_joe"
    type: "Payment"
    reason: "Credit card payment - avoid double counting"
    
  - source: "apple_card_nikita" 
    type: "Payment"
    reason: "Credit card payment - avoid double counting"
    
  - source: "chase_credit_card"
    type: "Payment"
    reason: "Credit card payment - avoid double counting"

  # Checking account payments to cards (to avoid double counting)
  - source: "chase_checking"
    description_contains: "Payment to Chase card ending in 4754"
    reason: "Payment to Chase credit card - avoid double counting"
    
  - source: "chase_checking"
    description_contains: "APPLECARD GSBANK PAYMENT"
    reason: "Payment to Apple Card - avoid double counting"
    