# Custom categorization rules
# These rules override the default category mapping

custom_rules:
  # Income identification
  - name: "Salary Income - Clockwise"
    conditions:
      source: "chase_checking"
      type: "ACH_CREDIT"
      description_contains: "CLOCKWISE"
    action:
      category: "Salary Income"

  - name: "Salary Income - PagerDuty"
    conditions:
      source: "chase_checking"
      type: "ACH_CREDIT"
      description_contains: "PAGERDUTY"
    action:
      category: "Salary Income"

  # Debt payments
  - name: "Large Check Payment (Debt)"
    conditions:
      source: "chase_checking"
      type: "CHECK_PAID"
      amount_max: -999
    action:
      category: "Debt Payments"

  # Childcare payments (ATM withdrawals)
  - name: "Childcare ATM Withdrawal"
    conditions:
      source: "chase_checking"
      type: "ATM"
      amount_max: -700  # Large ATM withdrawal
    action:
      category: "Childcare"

  # Housing costs
  - name: "Mortgage Payment"
    conditions:
      source: "chase_checking"
      description_contains: "ROCKET MORTGAGE"
    action:
      category: "Housing"

  - name: "HOA/Condo Fees"
    conditions:
      source: "chase_checking"
      description_contains: "DEARBORN PARK"
    action:
      category: "Housing"

  # Utilities
  - name: "Electric Bill"
    conditions:
      source: "chase_checking"
      description_contains: "ComEd"
    action:
      category: "Bills & Utilities"

  - name: "Gas Bill"
    conditions:
      source: "chase_checking"
      description_contains: "PEOPLES GAS"
    action:
      category: "Bills & Utilities"

  # Auto loan
  - name: "Auto Loan Payment"
    conditions:
      source: "chase_checking"
      description_contains: "Auto Loan"
    action:
      category: "Transportation"

  # Savings/Investment transfers
  - name: "Wealthfront Savings Transfer"
    conditions:
      source: "chase_checking"
      description_contains: "Wealthfront      EDI PYMNTS"
    action:
      category: "Savings"

# Merchant grouping rules (for combining similar merchants)
merchant_groups:
  "Amazon":
    patterns: ["AMAZON", "AMZN", "WHOLEFDS"]
    master_name: "Amazon"

  "Apple Services":
    patterns: ["APPLE.COM", "APPLE SERVICES"]
    master_name: "Apple"

  "Uber":
    patterns: ["UBER", "UBER EATS"]
    master_name: "Uber"

  "Starbucks":
    patterns: ["STARBUCKS", "SBX"]
    master_name: "Starbucks"

  "Target":
    patterns: ["TARGET", "TGT"]
    master_name: "Target"